### ISSUE TITLE
Uploading to stackage?

### ISSUE THREAD

**Issue by mstksg** [yogsototh/human-readable-duration#3]
Hi!  Thanks again for the work you put into this, it's been useful for me!  Just wondering if there any plans to put this package onto the [stackage](https://www.stackage.org/) package database? :)

(If you wanted to, it's as simple as [editing this file](https://github.com/fpco/stackage/edit/master/build-constraints.yaml))

**Comment by yogsototh** [comment]
It is already in stackage: https://www.stackage.org/lts-4.1/package/human-readable-duration-0.1.0.0

The last version 0.2.0.0 should appear soon enough in a nightly build and certainly in the next LTS (4.2).

Best!

**Comment by mstksg** [comment]
Ah thanks, I thought I looked, but I think I looked at the wrong snapshot.  Thanks!

**Comment by yogsototh** [comment]
You're welcome!
